### ISSUE TITLE
Authentication context for Azure AD

### ISSUE THREAD

**Issue by steve-prentice** [wlabarron/yourls-saml#3]
I'm trying to get this working for an Azure AD logon, but I keep getting an error like this:

AADSTS75011: Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'.

Googling around takes me to:

https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php

And it seems to suggest I should set:

'requestedAuthnContext' => false,

How could I get this working in your plugin please? I'm not sure what to do. Thanks!

**Comment by wlabarron** [comment]
I've not got details about this specific issue or setting, but you can add any extra settings you like to `settings.php`, inside the `$wlabarron_saml_settings` array. That array is the same as `$advancedSettings` in the code sample you've linked to.

**Comment by steve-prentice** [comment]
Ideal, thank you, that's given me the confidence to have a go... I've added this to the bottom of settings.php:

    // Security settings
    'security' => array (
        'requestedAuthnContext' => false,
    ),

And it's worked a treat, no more 'X509, MultiFactor' error.

**Comment by wlabarron** [comment]
Amazing, thanks for reporting back!
