### ISSUE TITLE
Error using SAML with certificate-based authenticacion

### ISSUE THREAD

**Issue by ihersua** [wlabarron/yourls-saml#8]
Hi,

I've implemente the plugin to use Entra ID as IDP. When trying to use certificate-based authentication I get this message:

AADSTS75011: Authentication method 'X509, MultiFactor, X509CertificateMultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the application owner.

Is there any way to change the authentication methods in the plugin to allow certificate-based authentication?

**Comment by wlabarron** [comment]
This might be possible through a configuration option. The `$wlabarron_saml_settings` array in the config file is passed straight through to the [SAML-Toolkits/php-saml](https://github.com/SAML-Toolkits/php-saml) library, so I'd suggest looking through their documentation or asking in their repo for specifics on how to set that up.

**Comment by ihersua** [comment]
Solve adding ` 'security' => array (
    'requestedAuthnContext' => false,
    ),` in the `$wlabarron_saml_settings` and then running `composer install`.

Thanks!
